version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "15673:15672"
      - "5673:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    volumes:
      - kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  pdfworkerservice:
    image: ${DOCKER_REGISTRY-}pdfworkerservice
    restart: always
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: PdfWorker/Dockerfile

  emailworkerservice:
    image: ${DOCKER_REGISTRY-}emailworkerservice
    restart: always
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: EmailWorker/Dockerfile

  smsworkerservice:
    image: ${DOCKER_REGISTRY-}smsworkerservice
    restart: always
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: SmsWorker/Dockerfile
      
  eventlogworker:
    image: eventlogworker
    restart: always
    depends_on:
      - rabbitmq
      - elasticsearch
    build:
      context: .
      dockerfile: EventLogWorker/Dockerfile

  webui:
    image: ${DOCKER_REGISTRY-}webui
    restart: always
    ports:
      - "8090:80"
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: WebUI/Dockerfile 

volumes:
  rabbitmq:
    driver: local
  elasticsearch:
    driver: local
  kibana:
    driver: local