version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp/Dockerfile

  mailworkerservice:
    image: ${DOCKER_REGISTRY-}mailworkerservice
    build:
      context: .
      dockerfile: MailWorkerService/Dockerfile

