version: '3.4'

services:
  audioplayer:
    image: boraakgn/ytdl-core-audio-player
    restart: always
    ports:
      - "8889:80"
    environment:
      - YT_AUDIO_SERVER_PORT=8888

  audioserver:
    image: boraakgn/ytdl-core-audio-info-server
    restart: always
    ports:
      - "8888:8080"


