version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  searchapi:
    image: ${DOCKER_REGISTRY-}searchapi
    build:
      context: .
      dockerfile: SearchApi/Dockerfile

  searchhandler:
    image: ${DOCKER_REGISTRY-}searchhandler
    build:
      context: .
      dockerfile: SearchHandler/Dockerfile
    environment:
      - HttpClientTimeout=60000

  searchtargetapi1:
    image: ${DOCKER_REGISTRY-}searchtargetapi1
    build:
      context: .
      dockerfile: SearchTargetApi/Dockerfile
    environment:
    - StoreId=1
    - Duration=40000

volumes:
  rabbitmq:
    driver: local