version: '3.4'

services:
  searchapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  searchhandler:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  searchtargetapi1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

